name: SGDuels
version: 0.0.1
author: AkabeX86
main: com.akabex86.main.Main
api-version: 1.18
depend: [ProtocolLib]
softdepend: [PlaceholderAPI,WorldGuard]

commands:
  sgduels:
    aliases: [duels,sgd,sg]
    permission: SGDuels.duels
    usage: /sgd help
    description: Main Command.
  arena:
    aliases: [config,edit,cfg]
    permission: SGDuels.admin
    usage: /arena help
    description: Arena Editor.
  spectate:
    aliases: [spec,watch]
    permission: SGDuels.mod
    usage: /spectate <player>
    description: Spectate Command (WIP).
  world:
    aliases: [mw,mworld]
    permission: sgduels.world
    usage: /world <world>
    description: World Teleport.
